name: Prod branches deletion
on:
  push:
    branches:
      - main

jobs:
  branch-deletion:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.G_TOKEN }}

      - name: Delete merged branch
        uses: koj-co/delete-merged-action@master
        with:
          branches: "production"
        env:
          GITHUB_TOKEN: "${{ secrets.G_TOKEN }}"

      - name: Delete branch in specific repository with a specific owner
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.G_TOKEN }}
          #owner: specific-owner
          #repository: specific-repository
          branches: production
          #suffix: -done